import { Ubuntu_Mono } from "next/font/google";
import "./globals.css";

// const inter = Inter({ subsets: ["latin"] });
const ubuntuMono = Ubuntu_Mono({ subsets: ["latin"], weight: ["400"]});
const content = ubuntuMono.className;

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={content}>{children}</body>
    </html>
  );
}
